[package]
name = "helium"
version = "0.1.0"
authors = ["MUsmanZahid <57581718+MUsmanZahid@users.noreply.github.com>"]
edition = "2018"

[dependencies]

[lib]
crate-type = ["rlib"]

[profile.release]
lto = true
opt-level = 3
overflow-checks = false
panic = "unwind"
